openapi: 3.1.0
info:
  title: NGSS Science Standards API
  version: 1.0.0
servers:
  - url: https://ngss-api.onrender.com
paths:
  /ngss:
    get:
      summary: Search NGSS standards
      operationId: searchNGSS
      parameters:
        - name: topic
          in: query
          required: true
          schema:
            type: string
          description: Science topic (e.g. "motion", "energy", "weather")
        - name: grade
          in: query
          required: true
          schema:
            type: string
          description: Grade level (e.g. "3", "5", "K")
      responses:
        '200':
          description: A list of matching NGSS standards
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        grade:
                          type: string
                        code:
                          type: string
                          description: NGSS identifier (e.g. "5-PS2-1")
                        description:
                          type: string
                          description: A summary of the standard
