openapi: 3.0.0
info:
  title: NGSS Standards API
  version: 1.0.0
  description: Search NGSS standards by grade and topic.
servers:
  - url: https://aquamarine-faithful-tango.glitch.me
paths:
  /ngss:
    get:
      operationId: getNgssStandards
      summary: Retrieve NGSS standards
      description: Returns a list of NGSS standards filtered by grade and topic keyword.
      parameters:
        - name: grade
          in: query
          required: true
          schema:
            type: string
          description: Grade level (e.g., k, 1, 2, 3, 4, 5)
        - name: topic
          in: query
          required: true
          schema:
            type: string
          description: Topic keyword to search in the description
      responses:
        '200':
          description: Successful response with matched standards
          content:
            application/json:
              schema:
                type: object
                properties:
                  standards:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                          example: "K-PS2-1"
                        description:
                          type: string
                          example: "Plan and conduct an investigation to compare the effects of different strengths..."
        '400':
          description: Missing or invalid parameters
